// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlertSystem.Models
{
    public partial class AlertAssign
    {
        public AlertAssign()
        {
            AlertCheck = new HashSet<AlertCheck>();
        }

        public int Id { get; set; }
        public int StaffId { get; set; }
        public int AlertId { get; set; }
        public DateTime AssignedDate { get; set; }
        public int AssignedBy { get; set; }
        public DateTime StaffNotified { get; set; }
        public string AlertStatus { get; set; }
        public int Createdby { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public bool RecordStatus { get; set; }

        public virtual Alert Alert { get; set; }
        public virtual ICollection<AlertCheck> AlertCheck { get; set; }
    }
}