// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlertSystem.Models
{
    public partial class Alert
    {
        public Alert()
        {
            AlertAssign = new HashSet<AlertAssign>();
        }

        public int Id { get; set; }
        public string PassengerName { get; set; }
        public string PassportNo { get; set; }
        public byte[] PassengerPhoto { get; set; }
        public bool? TravellingAlone { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Status { get; set; }
        public int AlertLevelId { get; set; }
        public string Nid { get; set; }
        public string Gender { get; set; }
        public int NationalityId { get; set; }
        public string FlightNo { get; set; }
        public DateTime FlightScheduledDate { get; set; }
        public DateTime? Eta { get; set; }
        public bool IsLuggageHit { get; set; }
        public string LuggagetagNumber { get; set; }
        public bool IsTroute { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public bool RecordStatus { get; set; }

        public virtual ICollection<AlertAssign> AlertAssign { get; set; }
    }
}