// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlertSystem.Models
{
    public partial class Nationality
    {
        public Nationality()
        {
            Alert = new HashSet<Alert>();
        }

        public int Id { get; set; }
        public string Nationality1 { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public bool RecordStatus { get; set; }

        public virtual ICollection<Alert> Alert { get; set; }
    }
}